// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7hStJohtWbU9_F3KDTHHuVxMEzgghVpw',
    appId: '1:386607039385:web:a014af238bbaf138c04908',
    messagingSenderId: '386607039385',
    projectId: 'meet-app-365fc',
    authDomain: 'meet-app-365fc.firebaseapp.com',
    storageBucket: 'meet-app-365fc.appspot.com',
    measurementId: 'G-BMJ3GBBX74',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASDBcgdMHx_xU2L6-X4VzeS9Wsftmbua8',
    appId: '1:386607039385:android:1e112ee4f3f9e32fc04908',
    messagingSenderId: '386607039385',
    projectId: 'meet-app-365fc',
    storageBucket: 'meet-app-365fc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfM-4ci_uJ_exco-nwIbn2TcvkFpve2CQ',
    appId: '1:386607039385:ios:f3740d65c2363cccc04908',
    messagingSenderId: '386607039385',
    projectId: 'meet-app-365fc',
    storageBucket: 'meet-app-365fc.appspot.com',
    iosClientId: '386607039385-hfile72982sbujo8c8j88h0qsl4le234.apps.googleusercontent.com',
    iosBundleId: 'com.example.meet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfM-4ci_uJ_exco-nwIbn2TcvkFpve2CQ',
    appId: '1:386607039385:ios:f3740d65c2363cccc04908',
    messagingSenderId: '386607039385',
    projectId: 'meet-app-365fc',
    storageBucket: 'meet-app-365fc.appspot.com',
    iosClientId: '386607039385-hfile72982sbujo8c8j88h0qsl4le234.apps.googleusercontent.com',
    iosBundleId: 'com.example.meet',
  );
}
